os: linux
sudo: false
language: perl
perl:
- '5.26'
before_install:
- cpanm Carton
install:
- cd Conch; carton install
script:
- cd Conch; carton exec prove -lpr t/
cache:
  directories:
  - Conch/local
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: 4LnUL0ygKCqDWt+LdGTDN99Ny5TQqfNdDSMyeRkwVqEo3MjZJfplLDbXLR8xVBKyxOVtK9NCJ+UdQ4qWmFSgduts3F0iWK9Cw8vjNoCXTv8Q/yTi1mrOq/LYvyAdYUeoBG7NUrYapFVr5drTDcdDEousHXB3HmL0Jj1az2PVXXtl/bta5AGwe7lNSIecQyGIJUIu8Y5D8Uehhszn9bA0kuZ0Ka/mT0x5XSrEhnfydZf6VB2UOx5NBicCHyegfHWRO4qjPiRjp8UPre+hYS+oCInLliv4tMO6v0bVjuy02tK5hTZn2AbL5B69b0B0EIYP7cvj61gj6nqoPxWPnCv8s823zU5GsN+Q5bG+OOE8yjLA3voK5U9OWRY3umKYNddSa3j9ZDwWytITwzd8t+C04f056zZh82Qxaeip1eWDK/JeIA6nsMH6mBmSlenElUdZq0C9AziaIVtasUudu1TSkJecnkWj2nutHtCPAAGs/in3t/Yki1ci4KxM3g/W1rDg0NOR53DbUK8W0+YPrhR+TMkj3fONjYk2e+se7VHxJQtxeUvLSG3MHh4JKfuYoX+DglcW5BNedRvQP2Oi0tUyr82Dmhbq8B7TH0vPKciu0szb5GwY09jzBDX2VTkwRHugAFohasiZmb/XYmkqZTJO3dxnWBlDpRV9CtkpjWHrfd8=
  on:
    tags: true
    repo: joyent/conch
notifications:
  recipients:
  - sungo@joyent.com
  email:
    on_success: change
    on_failure: always
